



<div className="paragraph">### </div>


  <div className="paragraph">In 2017, our city evicted 1,377 camps, and from January through October of 2018, 1,845 camps were evicted. Use the menu below to visualize the magnitude and location of sweeps across different neighborhoods in Portland (pink: 2016, yellow: 2017, orange: 2018).</div>
  <div className="paragraph"> </div>
#####

<div className="paragraph">To understand sweep-evictions at a neighborhood scale we subset the sweep-evictions to within the boundaries of Hosford-Abernethy, Buckman, and Kerns. These are the neighborhoods that contain the 77-block area of the Central Eastside Industrial District, several areas of which are swept on a regular basis, as part of a City-described "maintenance project" that refers to sweeps that regularly occur in a single location. The Central Eastside Industrial Council is proposing a self-imposed tax to create an"Enhanced Service District" that they are requesting approval for on January 17th.</div>
  <div className="paragraph">To understand sweep-evictions at a neighborhood scale, we zoom in to examine how they affect our unsheltered neighbors on a block by block basis. This represents all of the sites within the boundaries of Hosford-Abernethy, Buckman, and Kerns that have been swept, but many of the same sights have been swept repeatedly, week after week (see the map above for a visual idea of the density of campsite sweeps over time). If the 77-block area of the Central Eastside Industrial Council gets its "Enhanced Service District" approved on January 17th we expect the number of calls to the City for sweeps will go up, as has happened in so many other of these districts (<a href="https://poseidon01.ssrn.com/delivery.php?ID=170124119105002025099118124001079077122024024079020086078021123005121121108105121081017021040022038009060126027100094112000025055090056092048081112096001099027111029086011066083096023072107086095117025100004080015111105001098067116000105122117066123&EXT=pdf">Selben, 2018</a>).</div>
  <div className="paragraph"> </div>
#####

<div className="paragraph">In the last year, a vocal minority of Portlanders have requested increased policing and private security forces based on claims that (a) that the City and particular neighborhoods are experiencing an increase in person and property crimes because of inadequate resources allocated to policing, and/or (b) that the City is not allowing our police to fully enforce our laws with residents who live outside <em>(</em><a href="https://www.latimes.com/nation/la-na-portland-homeless-vigilantes-20181218-story.html"><em>Schmid, 12/29/2018</em></a><em>; </em><a href="https://www.portlandmercury.com/news/2018/10/11/23548160/hall-monitor-service-resistant"><em>Zielinksi, 10/11/2018</em></a><em>; </em><a href="https://www.kgw.com/article/news/local/enough-is-enough-needles-human-waste-at-montavilla-park-is-the-last-straw-for-neighbors/283-548982755"><em>Cook, 05/4/2018</em></a><em>; </em><a href="http://ceic.cc/eastworks/"><em>ceic.cc</em></a><em>; Sparling, </em><em>09/19/2018; </em><em>Bailey, </em><em>9/19/2018; </em><a href="https://www.montavilla.org/2018/09/11/enough-is-enough-portland-enoughisenoughpdx/"><em>montavilla.org</em></a><em>).</em></div>

  <div className="paragraph">The claim that Portland's crime rate is increasing is contentious. Our own exploration of crime report data and the Portland Police Bureau Budget Review of 2018-19 show that <strong>violent crimes and theft arrests have not increased, but remained stable over the past few years</strong>. This is corroborated by the City Budget Office and FBI analyses <em>(Shifley, 03/06/2018 </em><a href="https://www.portlandoregon.gov/cbo/article/675829">portlandoregon.gov</a><em>; </em><a href="https://www.wweek.com/news/courts/2017/10/04/fbi-statistics-show-crime-is-flat-or-down-across-portland-except-in-one-key-category/"><em>Shephard, 10/4/2017</em></a><em>).</em> This is contra to explicit claims made by organizations and residents that crime rates are rising, in order to justify the need for additional private security forces, neighborhood security patrols, or requests for that the City increase its policing budget<em> (</em><a href="https://www.latimes.com/nation/la-na-portland-homeless-vigilantes-20181218-story.html"><em>Schmid, 12/29/2018</em></a><em>; </em><a href="https://www.kgw.com/article/news/local/enough-is-enough-needles-human-waste-at-montavilla-park-is-the-last-straw-for-neighbors/283-548982755"><em>Cook, 05/4/2018</em></a><em>; Sparling, </em><em>09/19/2018; </em><a href="http://ceic.cc/eastworks/"><em>ceic.cc</em></a><em>; </em><a href="https://www.oregonlive.com/business/index.ssf/2018/01/downtown_portlands_paradox.html"><em>Burke, 2008; Marum, 01/07/2018</em></a><em>; </em><a href="https://www.koin.com/news/civic-affairs/pearl-district-residents-to-address-homelessness-crime/1635951060"><em>Haas, 12/03/2018</em></a><em>; </em><a href="https://www.koin.com/news/local/multnomah-county/neighbors-blame-wheeler-for-lack-of-response-to-homeless/1424501337"><em>Miller, 09/06/2018</em></a><em>).</em></div>

  <div className="paragraph">Police arrests of unhoused Portland residents were up 12% in a June analysis for 2018. Moreover, though houseless residents make up only 3% of the population, they accounted for 52% of all arrests in 2017<em>&mdash;</em>19% of which were for criminal trespass (mostly for unauthorized camping), and 42% of which involved procedural violations or warrants for unpaid fines or missed court dates <em>(</em><a href="https://www.oregonlive.com/portland/index.ssf/2018/07/portland_mayor_ted_wheeler.html"><em>Woolington, 6/13/2018</em></a><em>; </em><a href="https://www.oregonlive.com/expo/news/erry-2018/06/79b61635fd4450/portland_homeless_arrests_data.html"><em>Lewis & Woolington, 06/29/2018</em></a><em>; </em><a href="https://www.oregonlive.com/portland/index.ssf/2018/06/portland_homeless_accounted_fo.html"><em>Lewis & Woolington, 06/27/2018</em></a><em>)</em>. Most of the increase in Police calls and costly responses were for &lsquo;unwanted/suspicious' persons or welfare checks, many of those likely the result of anti-homeless calls (<a href="https://www.portlandoregon.gov/cbo/article/675829"><em>Shifley, 03/06/2018</em></a>). This suggests not only an increase in enforcement, but a disproportionate targeting of the houseless population for scrutiny and arrest.</div>

  <div className="paragraph">The City of Portland saw a 7% increase in total crime reports from 2016 to 2017, and a 3.5% increase in total crime reports from 2017 to 2018 (Jan-Oct). <strong>This is </strong><strong><em>not</em></strong><strong> normalized to the population growth that has occurred across Portland, and absolute crime report counts were used to look at increases only, rather than rankings or per capita growth. </strong>The rapid growth of Portland's population means that the crime rates per capita will have a smaller increase than the absolute number we report here.</div>
  <div className="paragraph"> </div>
#####


<div className="paragraph">The Central Eastside Industrial Council (CEIC, a local business group) claims that "increases in unwanted crime and grime, including a 64% increase in crimes against people and property in the past year, have pervaded the district and threaten Central Eastside's emerging reputation and business viability." Our findings dispute the CEIC's claim. <strong>Looking from 2015-2018 there is no significant upward trend in crime reports made in the Central Eastside Industrial District boundaries, and a comparison of all data available in 2017 and 2018 (January- October) shows only a 5.7% increase in crime reports. </strong>A time series model predicts no significant increase over the next year as well. Additionally, we request more transparency from the CEIC regarding data source and methodology, as this analysis does not replicate the crime statistics their proposal contains. When private security forces are invited to patrol public space,<strong> with none of the customary public oversight or accountability of public policing,</strong> historically targeted/over-policed populations are placed in a particularly vulnerable position.</div>

  <div className="paragraph">We used Venture Portland's business district boundary map to obtain a polygon of the boundaries for the CEID, and subset the crime reports data down to crime reports with lat/long coordinates that fall within those boundaries (<a href="http://ventureportland.org/business-districts/business-district-map/">ventureportland.org</a>). Crime reports without lat/long are not included in this report. We then subset out person and property crimes as the CEIC did, using the offense categories that are reported through the Portland Police Bureau (<a href="https://www.portlandoregon.gov/police/71978">portlandoregon.gov</a>). This gave us a total of all person and property crime reports for the CEID over the total period for which this data is available in a comparable format through the PPB (2015-2018: the PPB changed their data reporting practices from UCR to NIBRS in 2015 and so data prior to 2015 is not directly comparable; see <a href="https://www.portlandoregon.gov/police/71978">portlandoregon.gov</a>). With this dataset, we were unable to replicate their results.</div>
  <div className="paragraph">When running totals of crime report counts are taken into account from January through October, a comparison of the January-October 2017 period to January-October 2018 shows only a 5.7% increase in person and property crime (at the time of analysis, November/December 2018 was not yet available). From January-October 2016-2017, there was a -1.1% change in person/property crime reports. Total crime counts were not normalized to any population increase that happened during this time (which means the 5.7% increase would most likely be smaller, per capita). For all crime, the CEID saw a -1.6% change in crime reports from 2016-2017, and a 6.2% change from 2017-2018 (the difference is that society crimes are included in this subset, in addition to person and property crimes).</div>

#####
<div className="paragraph">Across all crime types, the three neighborhoods of Hosford-Abernethy, Buckman and Kerns (together) saw a 2.2% increase in total crime reports from 2016 to 2017, and a 1.2% decrease in total crime reports from 2017 to 2018 (Jan-Oct). The CEID boundaries (above) are a subset of these three neighborhoods, crossing the eastside of all three, so data from the Central Eastside Industrial District is subsumed in this section.</div>

  <div className="paragraph">The three geographic areas reported here all show change in crime from one year to the next in aggregate, absolute counts of crime reports. No area shows the 64% reported by the CEIC for the Central Eastside Industrial District.</div>
  <div className="paragraph">This section has engaged in a high level analysis at summarizing totals across Portland and the Central Eastside, and one deeper dive into trends over time in the CEID. Neighbor2neighbor plans a deeper dive into policing and crime reporting, and if you're interested in volunteering, please contact <a href="mailto:n2npdx@gmail.com">n2npdx@gmail.com</a>.</div>